### ISSUE TITLE
Why do HTTP HEAD requests request in a freak-out-and-die loop?

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-whosonfirst-s3#2]
Note: The same number / frequency of PUT requests are processed just fine...

```
$> ./sync -bucket com.mapzen.debug -credentials creds -root /usr/local/mapzen/whosonfirst-data/data/101
SKIP /716/257/101716257.geojson because it is unchanged
SKIP /721/173/101721173.geojson because it is unchanged
SKIP /724/103/101724103.geojson because it is unchanged
SKIP /723/001/101723001.geojson because it is unchanged
SKIP /715/191/101715191.geojson because it is unchanged
SKIP /727/001/101727001.geojson because it is unchanged
SKIP /725/099/101725099.geojson because it is unchanged
SKIP /719/001/101719001.geojson because it is unchanged
SKIP /713/063/101713063.geojson because it is unchanged
SKIP /720/001/101720001.geojson because it is unchanged
SKIP /726/387/101726387.geojson because it is unchanged
SKIP /722/057/101722057.geojson because it is unchanged
SKIP /712/265/101712265.geojson because it is unchanged
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x43f573]

goroutine 7 [running]:
com.mapzen/whosonfirst/s3.func·002()
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/com.mapzen/whosonfirst/s3/sync.go:124 +0x143
github.com/jeffail/tunny.func·001(0x67d620, 0xc208296000, 0x0, 0x0)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/jeffail/tunny/tunny.go:196 +0x67
github.com/jeffail/tunny.(*tunnyDefaultWorker).TunnyJob(0xc208038058, 0x67d620, 0xc208296000, 0x0, 0x0)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/jeffail/tunny/tunny.go:90 +0x50
github.com/jeffail/tunny.(*workerWrapper).Loop(0xc20803af90)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/jeffail/tunny/worker.go:54 +0x162
created by github.com/jeffail/tunny.(*workerWrapper).Open
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/jeffail/tunny/worker.go:80 +0x165

goroutine 1 [semacquire]:
sync.(*WaitGroup).Wait(0xc2080403d0)
    /usr/local/mapzen/golang/go/src/sync/waitgroup.go:132 +0x169
github.com/MichaelTJones/walk.Walk(0x7ffff897e83d, 0x2b, 0xc208028990, 0x0, 0x0)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/MichaelTJones/walk/walk.go:159 +0x2cb
github.com/whosonfirst/go-mapzen-whosonfirst-crawl/src/com.mapzen/whosonfirst.Crawler.Crawl(0x7ffff897e83d, 0x2b, 0xc20803acc0, 0x0, 0x0)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/whosonfirst/go-mapzen-whosonfirst-crawl/src/com.mapzen/whosonfirst/crawl.go:45 +0xcb
com.mapzen/whosonfirst/s3.Sync.SyncDirectory(0x782cd0, 0xb, 0xc2080e0000, 0x7ffff897e7ff, 0x10, 0xc208064400, 0x20, 0x20, 0xc2080c6000, 0x20, ...)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/com.mapzen/whosonfirst/s3/sync.go:91 +0x2e9
main.main()
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/bin/sync.go:58 +0x3d9

goroutine 5 [chan receive]:
main.func·001(0xc208058120)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/bin/sync.go:51 +0x5b
created by main.main
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/bin/sync.go:55 +0x357

goroutine 6 [chan send]:
github.com/jeffail/tunny.(*workerWrapper).Loop(0xc20803af60)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/jeffail/tunny/worker.go:51 +0xbf
created by github.com/jeffail/tunny.(*workerWrapper).Open
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/jeffail/tunny/worker.go:80 +0x165

goroutine 8 [chan send]:
github.com/jeffail/tunny.(*workerWrapper).Loop(0xc20803afc0)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/jeffail/tunny/worker.go:61 +0x232
created by github.com/jeffail/tunny.(*workerWrapper).Open
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/jeffail/tunny/worker.go:80 +0x165

goroutine 9 [select]:
net/http.(*persistConn).roundTrip(0xc20835e2c0, 0xc208029700, 0x0, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/http/transport.go:1082 +0x7ad
net/http.(*Transport).RoundTrip(0xc208186630, 0xc2083ea0d0, 0xc2082294a0, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/http/transport.go:235 +0x558
net/http.send(0xc2083ea0d0, 0x7fa2f16a7e38, 0xc208186630, 0x43, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc208230360, 0xc2083ea0d0, 0x43, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc208230360, 0xc2083ea0d0, 0x806a08, 0x0, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Do(0xc208230360, 0xc2083ea0d0, 0x773b50, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/http/client.go:174 +0xa4
github.com/goamz/goamz/s3.(*S3).run(0xc2080e0000, 0xc208382100, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/goamz/goamz/s3/s3.go:1015 +0x4eb
github.com/goamz/goamz/s3.(*Bucket).Head(0xc208382090, 0xc2083420c0, 0x1a, 0xc2080f80c0, 0x20, 0x0, 0x0)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/goamz/goamz/s3/s3.go:322 +0x1f3
com.mapzen/whosonfirst/s3.func·002()
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/com.mapzen/whosonfirst/s3/sync.go:122 +0x13e
github.com/jeffail/tunny.func·001(0x67d620, 0xc208342100, 0x0, 0x0)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/jeffail/tunny/tunny.go:196 +0x67
github.com/jeffail/tunny.(*tunnyDefaultWorker).TunnyJob(0xc208038068, 0x67d620, 0xc208342100, 0x0, 0x0)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/jeffail/tunny/tunny.go:90 +0x50
github.com/jeffail/tunny.(*workerWrapper).Loop(0xc20803aff0)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/jeffail/tunny/worker.go:54 +0x162
created by github.com/jeffail/tunny.(*workerWrapper).Open
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/jeffail/tunny/worker.go:80 +0x165

...

goroutine 229 [IO wait]:
net.runtime_pollWait(0x7f1c5a26bc18, 0x77, 0xc8207e8ab0)
    /usr/local/mapzen/golang/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203e5b10, 0x77, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitWrite(0xc8203e5b10, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/fd_poll_runtime.go:82 +0x36
net.(*netFD).connect(0xc8203e5ab0, 0x0, 0x0, 0x7f1c5a26b8f0, 0xc8207d9c60, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/fd_unix.go:114 +0x1f6
net.(*netFD).dial(0xc8203e5ab0, 0x7f1c583d7130, 0x0, 0x7f1c583d7130, 0xc8202acd20, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/sock_posix.go:137 +0x351
net.socket(0x7cf818, 0x3, 0x2, 0x1, 0x0, 0xc8202acd00, 0x7f1c583d7130, 0x0, 0x7f1c583d7130, 0xc8202acd20, ...)
    /usr/local/mapzen/golang/go/src/net/sock_posix.go:89 +0x411
net.internetSocket(0x7cf818, 0x3, 0x7f1c583d7130, 0x0, 0x7f1c583d7130, 0xc8202acd20, 0x0, 0x0, 0x0, 0x1, ...)
    /usr/local/mapzen/golang/go/src/net/ipsock_posix.go:160 +0x141
net.dialTCP(0x7cf818, 0x3, 0x0, 0xc8202acd20, 0x0, 0xc800000000, 0x0, 0x1, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/tcpsock_posix.go:171 +0x11e
net.dialSingle(0xc82076e200, 0x7f1c583d70a0, 0xc8202acd20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/dial.go:364 +0x3f5
net.dialSerial.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/dial.go:336 +0x75
net.dial(0x7cf818, 0x3, 0x7f1c583d70a0, 0xc8202acd20, 0xc8204735f8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/mapzen/golang/go/src/net/fd_unix.go:40 +0x60
net.dialSerial(0xc82076e200, 0xc8207e8aa0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/dial.go:338 +0x760
net.(*Dialer).Dial(0xc820473870, 0x7cf818, 0x3, 0xc8207d93c0, 0x14, 0x0, 0x0, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/dial.go:232 +0x50f
net.DialTimeout(0x7cf818, 0x3, 0xc8207d93c0, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/dial.go:193 +0xa2
github.com/goamz/goamz/s3.(*S3).run.func1(0x7cf818, 0x3, 0xc8207d93c0, 0x14, 0x0, 0x0, 0x0, 0x0)
    /usr/local/mapzen/go-mapzen-whosonfirst-s3/src/github.com/goamz/goamz/s3/s3.go:990 +0x94
net/http.(*Transport).dial(0xc820331ef0, 0x7cf818, 0x3, 0xc8207d93c0, 0x14, 0x0, 0x0, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/http/transport.go:499 +0x79
net/http.(*Transport).dialConn(0xc820331ef0, 0x0, 0x81e1c0, 0x5, 0xc8207d93c0, 0x14, 0xc82042e240, 0x0, 0x0)
    /usr/local/mapzen/golang/go/src/net/http/transport.go:596 +0x19a9
net/http.(*Transport).getConn.func4(0xc820331ef0, 0x0, 0x81e1c0, 0x5, 0xc8207d93c0, 0x14, 0xc820540540)
    /usr/local/mapzen/golang/go/src/net/http/transport.go:549 +0x66
created by net/http.(*Transport).getConn
    /usr/local/mapzen/golang/go/src/net/http/transport.go:551 +0x265
```

**Comment by thisisaaronland** [comment]
Go is weird. See also: https://github.com/whosonfirst/go-mapzen-whosonfirst-s3/commit/e1398cbb9454af4cf921e535f9f43e34dbb8beeb
